// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwUu81o98zzEwCvzil9KwGnOWGHNeiEts',
    appId: '1:35879799357:web:de04e06d417905dec2f854',
    messagingSenderId: '35879799357',
    projectId: 'myrenthubori',
    authDomain: 'myrenthubori.firebaseapp.com',
    storageBucket: 'myrenthubori.appspot.com',
    measurementId: 'G-TKW3FWBWC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvObBIYYIEmC6ZYG4J6PfPOhthE7EaE60',
    appId: '1:35879799357:android:b03083082a8f9fb0c2f854',
    messagingSenderId: '35879799357',
    projectId: 'myrenthubori',
    storageBucket: 'myrenthubori.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwlMbGpdvIPz4QSMg061e-X1NNVQGJPoE',
    appId: '1:35879799357:ios:d293a903836c5af5c2f854',
    messagingSenderId: '35879799357',
    projectId: 'myrenthubori',
    storageBucket: 'myrenthubori.appspot.com',
    iosBundleId: 'com.bitwisetech.myrenthub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwlMbGpdvIPz4QSMg061e-X1NNVQGJPoE',
    appId: '1:35879799357:ios:270a9c506352142ac2f854',
    messagingSenderId: '35879799357',
    projectId: 'myrenthubori',
    storageBucket: 'myrenthubori.appspot.com',
    iosBundleId: 'com.example.myrenthub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwUu81o98zzEwCvzil9KwGnOWGHNeiEts',
    appId: '1:35879799357:web:036415c7fd613563c2f854',
    messagingSenderId: '35879799357',
    projectId: 'myrenthubori',
    authDomain: 'myrenthubori.firebaseapp.com',
    storageBucket: 'myrenthubori.appspot.com',
    measurementId: 'G-45F7SGRMLQ',
  );
}
